---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by virtualkingdom.
--- DateTime: 2022/5/8 13:57
---



--再一个函数中写两个同名变量，一个全局变量和一个局部变量，将两个不同做作用域的相同变量搭载屏幕上
function firstLuaMethod()
    local bianliang = "本地变量"
    print(bianliang)
    bianliang = "全局变量"
    print(bianliang)
    -- local bianliang = "本地变量"
    -- bianliang = "全局变量"
    -- print(bianliang) 这样写输出结果只显示全局变量，本地变量没有生效
end
firstLuaMethod()
print("1123".."1232")


tab1 = {key1 =  "value1",key2 = "value2",100}

--print("tab1的值 = "..tab1)
print(tab1)
print(tab1.key2..tab1.key1)
print(tab1["key2"]..tab1["key2"])


tab2 = {key1 = "value1",key2 = "value2"}
print(tab2)
tab2["key3"] = "value3"
tab2.key4 = "value4"
--tab2.key4 = nil
tab2[-1] = 1000
tab2[0] = 2000
tab2[123] = 3000
--tab2[123] = nil
--tab2 = nil
--print(tab2)

-- 注意 key,val 是逗号不是点
--for key,val in pairs(tab2) do
--    print(key..":"..val)
--end

for key,value in pairs(tab2) do
    print(key..":"..value)
end










